# Copyright IBM Corp. All Rights Reserved.
# Modified by Kim Woo Jae
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: jnu.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Manager
    Domain: manager.jnu.com
    EnableNodeOUs: true
    Template:
      Count: 2
  - Name: Student
    Domain: student.jnu.com
    EnableNodeOUs: true
    Template:
      Count: 2
